### ISSUE TITLE
Hyperspectral workflow Tutorial Fail

### ISSUE THREAD

**Issue by fbtxst** [danforthcenter/plantcv#1310]
Hi all,

I'm trying to execute the [hyperspectral tutorial code](https://plantcv.readthedocs.io/en/v3.11.0/hyperspectral_tutorial/#Hyperspectral-script), but I was unable to complete the process due to an unexpected error. See below

Traceback (most recent call last):
  File "plantcv_script.py", line 70, in <module>
    main()### Main workflow
  File "plantcv_script.py", line 48, in main
    id_objects, obj_hierarchy = pcv.find_objects(img=index_array_gdvi.array_data, mask=gdvi_thresh)
  File "/Users/fabio/opt/anaconda3/envs/myEnv/lib/python3.8/site-packages/plantcv/plantcv/find_objects.py", line 33, in find_objects
    objects, hierarchy = cv2.findContours(mask1, cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)[-2:]
cv2.error: OpenCV(4.8.0) /Users/runner/work/opencv-python/opencv-python/opencv/modules/imgproc/src/contours.cpp:197: error: (-210:Unsupported format or combination of formats) [Start]FindContours supports only CV_8UC1 images when mode != CV_RETR_FLOODFILL otherwise supports CV_32SC1 images only in function 'cvStartFindContours_Impl'

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Run plantcv_script.py attached (python plantcv_script.py -i /your/path/raw -o./output-images -r results.txst -w -D 'print')
2. See error

**Expected behavior**

**Local environment (please complete the following information):**
 - OS: [macOS]

**Additional context**
[plantcv_script.py.zip](https://github.com/danforthcenter/plantcv/files/12157604/plantcv_script.py.zip)
PS: I'm pointing to the actual HS image (raw) and not the raw.hdr

**Comment by HaleySchuhl** [comment]
Hi! Without a sample image, I'm unable to replicate this error locally. Are you getting a mask in line 42 prior to this step that you are satisfied with? 
`    gdvi_thresh = pcv.threshold.binary(gray_img=index_array_gdvi.array_data, threshold=150, max_value=255)` ?

**Comment by fbtxst** [comment]
Hi Haley,

I appreciate your prompt response. You can download a test image from this [link](https://drive.google.com/drive/folders/1Aqx2HOJyuGiJzLjTye4p9KkjeqyQZKli?usp=sharing.)

Regarding your question, I'm facing the same outcome regardless of whether the threshold is set to 50 or 250. See images attached. Moreover, it seems that the pseudo RGB isn't correct either. Do you have any insights into what might be missing here?

![3_pseudo_rgb](https://github.com/danforthcenter/plantcv/assets/110848280/95170b99-58fa-46e8-a460-bfb43152cca9)
![5GDVI_index](https://github.com/danforthcenter/plantcv/assets/110848280/e9f7479c-bc29-44f3-b0d6-15d0bcfd5b0c)
![7_binary_threshold_250](https://github.com/danforthcenter/plantcv/assets/110848280/a6eeb35d-fd8c-4e25-91bf-94c74c5166a4)
![8_roi](https://github.com/danforthcenter/plantcv/assets/110848280/f3dbabf3-3c9b-489a-846e-5d8a0b8af62b)

**Comment by fbtxst** [comment]
Hi Haley, I'm eager to proceed with testing PlanCV with HSI and was wondering if you were able to replicate the error on your end.

**Comment by HaleySchuhl** [comment]
Hi @fbtxst thank you for circling back! I haven't gotten an opportunity to look at this again but I can take a look today.

**Comment by HaleySchuhl** [comment]
Looking at the .py workflow, it looks like your `main` function is getting defined twice? This is unrelated to the segmentation issue.

I also noticed that the header file includes a `default bands` field which PlantCV uses to make the pseudo_rgb when available. The difference to other images I've seen is that they're listed in decreasing order rather than increasing so I suppose this could be causing the unexpected pseudo_rgb result but changing the order manually didn't seem to make a difference.

Regarding segmentation, the gdvi index appears to have larger values in the background than within the plant pixels, so this index will likely not be able to segment the plant out. I tried a few difference indices and `pcv.spectral_index.ari` seemed to have a more promising result, but there are many more indices that might be even better for your dataset. I highly recommend using a jupyter notebook to test various indices and threshold levels until you are satisfied with the binary mask. Our tutorial workflow unfortunately will not work on your images without customization.
