### ISSUE TITLE
PlantCv / OpenCV2 on raspberry pi 3 Jessie

### ISSUE THREAD

**Issue by MjBordalo** [danforthcenter/plantcv#136]
Hi guys,

So i want to run PlantCV on my pi3. As I have read on issue #130 PlantCv does not work with openCV3 and i dont really find tutorials to install OpenCV2 in raspberry pi.

I have tried unsuccessfully to install plantCV as the normal linux installation tutorial suggests.
Ideias?
Thanks in advance

**Comment by nfahlgren** [comment]
My understanding is that on Jessie you can run `sudo apt-get install libopencv-dev python-opencv` to install OpenCV 2.4.9

**Comment by MjBordalo** [comment]
Trying..
the `sudo python setup.py install ` command is taking forever+10min with some warnings like:
```
Warning: distutils distribution has been initialized, it may be too late to add a subpackage skimageno previously-included directories found matching 'doc/build'
no previously-included directories found matching 'doc/gh-pages'
In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
                 from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from skimage/_shared/interpolation.c:284:
/usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2:
```

**Comment by nfahlgren** [comment]
Raspberry Pis are relatively slow compared to servers, so building the package dependencies may take some time. As long as there are no errors the warnings should be okay.

**Comment by MjBordalo** [comment]
I got this at the end of running `sudo python setup.py install `
```
pi@raspberrypi:~/plantcv $ Warning: distutils distribution has been initialized, it may be too late to add a subpackage skimageno previously-included directories found matching 'doc/build'
-bash: Warning:: command not found
pi@raspberrypi:~/plantcv $ no previously-included directories found matching 'doc/gh-pages'
-bash: no: command not found
pi@raspberrypi:~/plantcv $ In file included from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1761:0,
-bash: In: command not found
pi@raspberrypi:~/plantcv $                  from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
from: can't read /var/mail//usr/lib/python2.7/dist-packages/numpy/core/include/numpy/ndarrayobject.h:17,
pi@raspberrypi:~/plantcv $                  from /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
from: can't read /var/mail//usr/lib/python2.7/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
pi@raspberrypi:~/plantcv $                  from skimage/_shared/interpolation.c:284:
from: can't read /var/mail/skimage/_shared/interpolation.c:284:
pi@raspberrypi:~/plantcv $ /usr/lib/python2.7/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2:
```

Then i tried: ` python -c 'import plantcv'` 

and got:
``` pi@raspberrypi:~/plantcv $ python -c 'import plantcv'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "plantcv/__init__.py", line 27, in <module>
    from watershed import watershed_segmentation
  File "plantcv/watershed.py", line 7, in <module>
    from scipy import ndimage as ndi
ImportError: No module named scipy
```
Thus i tried 
```
pi@raspberrypi:~/plantcv $ pip install --user scipy
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

```

And also similiar if i just run `pip`. I think i have a problem with pip no? I also tryed to upgrade it and install via https://pip.pypa.io/en/stable/installing/ . But similiar erros appear.
Should i try to unistall it and install it again? (how?)

**Comment by MjBordalo** [comment]
I end up unistalling pip  `apt-get remove python-pip` and reinstall
![image](https://cloud.githubusercontent.com/assets/24882807/24771249/c7161a64-1b04-11e7-8022-408b5067cfd6.png)
 it from several ways. I also had to install some dependencies described in #134 sometimes using pip other times with `sudo apt-get install python-dendencyname`.
It was not a quite scientific method so i cannot explained you better.
It is working tough. So it is possible.

**Comment by nfahlgren** [comment]
Thanks @MjBordalo. I'm working through installing it on Jessie now too and will add the instructions to the Installation guide. I'm at the stage of running package updates, so I have not gotten to any of the PlantCV stuff yet, but I will use your experiences above as a guide.

**Comment by MjBordalo** [comment]
Nice @nfahlgren . Let me know when you are done so i can keep that info

**Comment by MjBordalo** [comment]
@nfahlgren  did you end u doing a RPi installation tutorial for plantCV?
