### ISSUE TITLE
parallel pipeline for image series

### ISSUE THREAD

**Issue by dschneiderch** [danforthcenter/plantcv#423]
New issue for second question in #422   Should have been separate, sorry.

Original relevant post:
> I took a look at the parallel version for flat files and of course I've been labeling my files from lemnabase differently from you. I am using format code {0}-{3}-{1}-{6} which corresponds to plantid-measurement label-timestamp-camera label whereas you have it setup with measurement label and timestamp flipped.
> Anyway to work on making this more flexible?
> Is this going to iterate through every timestamp?
> 
> here is my repo: https://github.com/dschneiderch/testpipeline

@HaleySchuhl  reply:

> For parallelization over a flat file directory you'll need to specify the labeling format. For example
> -a filename -f id_measurementlabel_timestamp_camera. We do aim to make this more flexible and allow users to provide personalized metadata names outside of the "valid metadata" options. We plan to wrap up v3 soon so this likely won't be implemented until PlantCV v4.
> 
> The default is to iterate through every .png file in the directory but there is the match metadata functionality to filter through files. There is a --dates option that is intended to limit the dates of interest but I've run into problems with this functionality before and haven't been able to successfully debug it.

**Comment by dschneiderch** [comment]
@HaleySchuhl  I think I figured out the metadata names but I had to look in the source. is this documented anywhere at plantcv.readthedocs.io?

So I ran: 
```
plantcv-workflow.py \
-d data/psII \
-a filename \
-p scripts/psii.py \
-j output-parallel.json \
-i debug/parallel \
-f plantbarcode-measurementlabel-timestamp-camera \
-l '-' \
-M measurementlabel:SILK_dark \
-t png
```

However, I get an unknown error:

```
$ ./scripts/run_psii.sh 
Starting run 2019-07-29_10-12-54

Building job list... 
Job list will include 80 images

took 0.35505104064941406

Processing images...
Traceback (most recent call last):
  File "C:/Users/dominikschneider/Miniconda3/envs/test-environment/Scripts/plantcv-workflow.py", line 4, in <module>
    __import__('pkg_resources').run_script('plantcv==3.5.0+16.g5b9908c.dirty', 'plantcv-workflow.py')
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\site-packages\pkg_resources\__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\site-packages\pkg_resources\__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "c:\users\dominikschneider\miniconda3\envs\test-environment\lib\site-packages\plantcv-3.5.0+16.g5b9908c.dirty-py3.7.egg\EGG-INFO\scripts\plantcv-workflow.py", line 317, in <module>
    main()
  File "c:\users\dominikschneider\miniconda3\envs\test-environment\lib\site-packages\plantcv-3.5.0+16.g5b9908c.dirty-py3.7.egg\EGG-INFO\scripts\plantcv-workflow.py", line 290, in main
    pcvp.multiprocess(jobs, args.cpu)
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\site-packages\plantcv-3.5.0+16.g5b9908c.dirty-py3.7.egg\plantcv\parallel\multiprocess.py", line 15, in multiprocess
    p = mp.Pool(processes=cpus)
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\dominikschneider\Miniconda3\envs\test-environment\lib\multiprocessing\spawn.py", line 172, in get_preparation_data
    main_mod_name = getattr(main_module.__spec__, "name", None)
AttributeError: module '__main__' has no attribute '__spec__'
```

The script does produce a text file with the metadata from each imagefile. I notice that timestamp value is `2018` so the script only captured the first parto the timestamp.
`data/psII\\A1-SILK_dark-2018-12-10 20_01_50-PSII0_1_0_0.png` 
retrospectively I guess it delimited on the '-' inbetween yr,mth,dy. However, in the docs https://plantcv.readthedocs.io/en/stable/pipeline_parallel/ you have the exact same timestamp format.  does that doc example work correctly?


```{json}
{
  "metadata": {
    "camera": {
      "label": ["camera identifier"],
      "datatype": ["<class 'str'>"],
      "value": ["12"]
    },
    "imgtype": {
      "label": ["image type"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "zoom": {
      "label": ["camera zoom setting"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "exposure": {
      "label": ["camera exposure setting"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "gain": {
      "label": ["camera gain setting"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "frame": {
      "label": ["image series frame identifier"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "lifter": {
      "label": ["imaging platform height setting"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "timestamp": {
      "label": ["datetime of image"],
      "datatype": ["<class 'datetime.datetime'>"],
      "value": ["2018"]
    },
    "id": {
      "label": ["image identifier"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "plantbarcode": {
      "label": ["plant barcode identifier"],
      "datatype": ["<class 'str'>"],
      "value": ["A1"]
    },
    "treatment": {
      "label": ["treatment identifier"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "cartag": {
      "label": ["plant carrier identifier"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "measurementlabel": {
      "label": ["experiment identifier"],
      "datatype": ["<class 'str'>"],
      "value": ["SILK_dark"]
    },
    "other": {
      "label": ["other identifier"],
      "datatype": ["<class 'str'>"],
      "value": ["none"]
    },
    "image": {
      "label": ["image file"],
      "datatype": ["<class 'str'>"],
      "value": ["data/psII\\A1-SILK_dark-2018-12-14 20_01_53-PSII0_30_0_0.png"]
    }
  },
  "observations": {}
}
```

**Comment by nfahlgren** [comment]
I don't think we currently list the metadata terms in the online documentation, but they are listed when you run `plantcv-workflow.py --help`.

I have to look into the error you are getting, it's coming from the Python multiprocess package.

**Comment by nfahlgren** [comment]
On the filename front, since you are specifying `-` as your metadata delimiter it's breaking up the date. Our default delimiter is `_` which is why the YYYY-MM-DD format is preserved as one metadata item in our use case.

What we can do with some reworking (and there is reason to do this anyway) is add more metadata terms like `year`, `month`, `day`, etc. Might need to think on that some more.

**Comment by dschneiderch** [comment]
The online docs example is misleading  :-)

```
AABA002948-2014-03-14 03_29_45-Pilot_031014-VIS_TV_z3500.png

    Plant ID = AABA002948
    Timestamp = 2014-03-14 03_29_45
    Measurement Label = Pilot_031014
    Camera Label = VIS_TV_z3500
```

**Comment by dschneiderch** [comment]
Also,
> The default is to iterate through every .png file in the directory but there is the match metadata functionality to filter through files. 
From what I can tell, this just lets you filter by metadata, but doesn't let you process more than 1 file at a time.

for example, I have 
`A1-silk_dark-20181212_010304-PSII1_0_0.tif` 
`A1-silk_dark-20181212_010304-PSII2_0_0.tif`
`A1-silk_dark-20181212_010304-PSII5_0_0.tif` 
`A1-silk_dark-20181212_010304-PSII6_0_0.tif` 
`A1-silk_dark-20181212_010304-PSII7_0_0.tif` 
`A1-silk_dark-20181212_010304-PSII8_0_0.tif` 
`A1-silk_dark-20181212_010304-PSII9_0_0.tif` 
`A1-silk_dark-20181212_010304-PSII10_0_0.tif` 

I need to iterate through the timestamp (so the above would be one group) but process pairs of images. 1 and 2 are special, so my pairs are 5,6; 7,8; 9,10.  additionally, each of my latter pairs need 1,2 for certain calcs. I'm looking at --coprocess but that is specifically for imgtype and I'd need to process PSII1_0_0 etc with a wildcard.

**Comment by nfahlgren** [comment]
We used to have a way to process the fluorescence images (3 in our case) but it's true that right now there's not built-in way for `plantcv-workflow.py` to build a job with multiple inputs like that, other than the `coprocess` method that can pair two image types. 

My thinking is that this is about processing an image stack (or series), even if the "frames" are stored as separate images. So what's a good way to label the images in a series so that we can find all the images that belong together? I don't think a wildcard would work in your case because the only difference between the image names is the `PSII#`, but how would we define a generalized method for pairing 1 with 2, etc.? Or what if someone else has 3 or more in a series?

**Comment by dschneiderch** [comment]
to start, i think a custom date format would be a good argument. Then you can also extract the date before parsing the metadata.

ultimately, we need to iterate based on any metadata instead of iterating on every image. It would be like groups in R or pandas.

So in my example, 

--group measurementlabel,timestamp,cartag

where measurementlabel = silk_dark
cartag = A1

That should give me all of my PSII# images at once. Then I setup my pipeline with -i1, -i2, ... -i8
Not really ideal because now the user has to setup loop(s) to get the various image pairs.

**Comment by nfahlgren** [comment]
It's been awhile since I used the LemnaTec import/export tool, but what about using underscores between metadata fields since they use dashes in the datetime field? Might be a moot point because I know there's always the issue of dealing with data already in-hand, plus some systems out there might not let you control the output naming at all. So we could definitely think about how to expand the flexibility. Not sure how easy it would be to get into pattern matching. We probably don't want users to have to input regular expression patterns, but I have a feeling datetime formats could get pretty complicated. E.g. what if someone just has a Unix epoch timestamp (one big integer) instead of some combination of ymd hms?

**Comment by nfahlgren** [comment]
I think I sort of get your second point about having grouping terms but I'm not following the iteration over metadata part. That is what we do right?

Our current process looks like this:

* Given: input directory
* Iterate over all image names to collect metadata (uses the `meta` flag information to parse the filenames)
* Decide whether to add the image to the job stack: This is done using the `match` flag of key:value pairs
* Build jobs

So definitely there is the easy case where a job only needs one input image, we can simply build a job for each and we know we need to map the image to the `--image` option in the user-provided PlantCV script.

I agree with you that it's not optimal to have the user put loop-logic in their script, so ideally the job builder could have some smarter logic to build more complex tasks. But I think this only works if the images can be tagged with metadata to achieve this in some way. I think the way we name the PSII images could work, in one snapshot we have three files like this:

```
FLUO_TV_h630_p1500_g100_10554_0.png
FLUO_TV_h630_p1500_g100_10554_1.png
FLUO_TV_h630_p1500_g100_10554_2.png
```

I think if we added a metadata term for the last field (0, 1, 2, etc.) we could group these three images into a series. Or maybe we don't even need that because the image ID (10554) is the same for all of these and we could group on that.

Another idea might be a user-provided metadata mapping input. I'm not sure in your case how many pairs there are or what they refer to exactly, but let's take our example snapshot above:

```
--mapping series:0:fdark,series:1:fmin,series:2:fmax
```

Not sure if this is similar to yours but if so:

```
--mapping series:PSII1:fmin,series:PSII2:fmax
```

Or something like that. Could be an input file instead. Then maybe the mappings can get passed as named arguments to the user script where the job builder then sets:

```
script --fmin image1.png --fmax image2.png
```

**Comment by dschneiderch** [comment]
Actually, lemnatec date uses both - and _ and " ". Wonderful, i know. e.g. 2019-07-06 10_10_10
That is one thing I can not control in the output without doing a batch rename afterwards. I'm surprised that you don't have that issue even with the LTDBextractor but it looks like you are specifying ('%Y-%m-%d %H:%M:%S') which I take it is the format on the server. I want to switch to using your extractor function but at the moment I'm also trying to make this workflow work with a none lemnatec system

for custom date format, i meant the codes found here. personally I've found them to be intuitive but I realize that's not a common sentiment :)
https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior

I see now though that there is no epoch format.
Py3.3 has a timestamp method now to output epoch seconds. Conversion from timestamp requires knowledge of the timezone to be unambiguous.
https://docs.python.org/3/library/datetime.html?highlight=re#datetime.datetime.timestamp
Can we check for Epoch format and treat that differently than other formats which would just use the builtin date parser based on the format code?

**Comment by nfahlgren** [comment]
Ah I see, makes sense. I built this separate Python extractor tool to get data out of our database (https://github.com/danforthcenter/pheno-data-service) so I can change the datetime format. Sorry, just saw that that GitHub repo has no documentation...but if you are ever interested in trying it out or whatnot happy to chat about it.

**Comment by dschneiderch** [comment]
@nfahlgren 
my point was that groups of metadata can act as unique identifiers for a series. for example FLUO_TV_h630_p1500_g100 is functionally the same as the identifier 10554 (potentially?)

in my case, the timestamp is unique for each series. but I would want to use timestamp and cartag at least.


How would you expand
`--mapping series:PSII1:fmin,series:PSII2:fmax`
to then iterate over pairs? images with PSII3 and higher are iterated on?

regarding an external mapping file, I currently use something like this with my scripts:
https://github.com/dschneiderch/WalzPSIIProcessing/blob/master/example_data/pimframes_map.csv
I read this in as a dataframe, join it to my metadata dataframe on column imageid, which is the final number behind PSII#
Then I loop over cartag,timestamp,parameter to process my images. This combo of 3 tags always gives 2 images. if parameter = FvFm then I write Fm and Fv/Fm to disk and read it back in when I need it to compute e.g. NPQ for the other parameters. 

also, fyi, images 1,2 are Fo, Fm.  images 3,4 are unused. images 5,6 and up are pairs of minimal and maximum fluorescence, respectively. If Fo and Fm are measured, they are stored again in 5,6.  This is from the WALZ PAM instrument.

**Comment by dschneiderch** [comment]
> 
> 
> Ah I see, makes sense. I built this separate Python extractor tool to get data out of our database (https://github.com/danforthcenter/pheno-data-service) so I can change the datetime format. Sorry, just saw that that GitHub repo has no documentation...but if you are ever interested in trying it out or whatnot happy to chat about it.

Is this different than the phenofront format?

**Comment by nfahlgren** [comment]
Hi @dschneiderch, sorry for the delay. The tool linked above outputs data in "phenofront" format (named after a predecessor tool).

**Comment by nfahlgren** [comment]
I want to try to summarize two ideas here.

**Goal**: Identify which images belong in a group (i.e. need to be processed by the same workflow instance)

**Grouping**: A group of images would be defined by a unique grouping of metadata terms. The group of images could be passed to a workflow script. The script would have to deal with how to treat the group. The input could simply be passed as a comma-separated list of images to the `--image` option in the workflow script. The user would know best how to deal with the image series/group, so this makes sense. I think this would not be super hard to implement, the biggest change would be in the metadata parser.

**Mapping**: Define how metadata terms and values are mapped to named inputs in a workflow script. A downside of this method is that it could get quite verbose, particularly in the example PSII image set above where there are 8 different mappings in principle. An upside is that it is more readable/descriptive and probably requires a little less programming on the user script side of things (at least in terms of parsing which image is which), although argument parsing becomes less standard. Very little would need to change with the metadata parser but the job builder would become quite a bit more complicated I think.

I don't have a strong sense for which method might be preferable from the user side. Possibly both could be implemented and even work together? 

Other changes to `plantcv-workflow.py` proposed above and/or that might help:

* Other ways to parse metadata when a consistent delimiter is not used (e.g. datetime issue above). Maybe this won't be so hard with the datetime part: https://stackoverflow.com/questions/3276180/extracting-date-from-a-string-in-python
* It's been discussed before, but are we at a point where it would be easier to use a configuration file to input information to `plantcv-workflow.py` instead of a lot of command-line arguments?
* I keep thinking there is a way we could make the `options` function (`argparse` parser) in the user scripts something that they can import from PlantCV and that we could build automatically, taking into account the discussion above.

**Comment by nfahlgren** [comment]
Hi @AdamDimech, good questions. A bit of backstory, as you know, a developer here wrote PhenoFront to allow us to access data in the LemnaTec database without using the LemnaDB Import/Export tool. The structure of how the data was output by PhenoFront was decided by that developer/team. When I wrote the tool you are using I maintained the same structured output because we had already written a PlantCV method to read data in that format, hence the name. Note that we could define a completely different output structure as makes sense to the community.

The important aspects of the format from the adapter (`-a phenofront`) point of view in `plantcv-workflow.py`:
* The entire experiment output needs to be contained in a directory (input to the `-d` option)
* Within that directory there must be a CSV file called `SnapshotInfo.csv` and there are snapshot directories called `snapshot<snapshot ID>`.
* The image names themselves mostly do not matter but any metadata that needs to be extracted from the image names needs to be separated by a consistent delimiter character (more on that below).

The CSV file is a table with the following headers:
`experiment,id,plant barcode,car tag,timestamp,weight before,weight after,water amount,completed,measurement label,tag,tiles`

The ID column is the LemnaTec snapshot ID and we expect that there is a corresponding folder called `snapshot<id>`. The `tiles` column is a semicolon-delimited list of image names (without the extension). The path to each image is derived from the CSV file with the pattern:

`<dir>/snapshot<id>/<img>.<type>`

The contents of the CSV file are all from the LemnaTec database. So when you see the lline:

```python
image_name = row['camera_label'] + '_' + str(row['tiled_image_id']) + '_' + str(row['frame'])
```

`row` is a single database entry and the fields being used from the database are `camera_label` (what the system operators define as the image name prefix on the LemnaControl computer), `tiled_image_id` (LemnaTec's image ID for this image, and `frame` (usually just zero, but there are some snapshots that have image series with more than one image, confusingly different than rotation angles).

Other data from the database could be added to the image names (e.g. timestamp), but with the phenofront adapter we read both the CSV file and the image names, so it would be duplicated information.

Above I said the image names do not really matter. For both the phenofront and filename adaptors we parse metadata from the image filenames. That means there's no fixed naming system required per se. You can use the `-f` option to define how the images are named using the "valid metadata" vocabulary we defined in `plantcv-workflow.py` (https://plantcv.readthedocs.io/en/stable/pipeline_parallel/, Valid Metadata section). So in your case that might look like:

```
0-deg_7642348_0.png
-f frame_id_other
```

**Comment by HaleySchuhl** [comment]
I think that since we added regex format for flexibility, especially with timestamp formats, in #454 this issue can get closed.. at least for now!

**Comment by dschneiderch** [comment]
actually, the underlying issue here is not resolved. the parallel package does not allow you to process multiple images at a time except very limited functionality with --coprocess. The functions in #426 aren't that useful until `plantcv-workflow.py` can accept a group of images, or however we want to call it. I believe at some point @nfahlgren wanted to tackle it for pcv4.

**Comment by dschneiderch** [comment]
@nfahlgren curious if this is on a roadmap?

**Comment by nfahlgren** [comment]
Sorry @dschneiderch, I haven't had a chance to work on this yet. We could prioritize this over some parallelization stuff I have been working on since it fits into the current `plantcv-workflow.py` paradigm.

Looking back over the conversation, in your case you have all the PSII files:

```
A1-silk_dark-20181212_010304-PSII1_0_0.tif
A1-silk_dark-20181212_010304-PSII2_0_0.tif
A1-silk_dark-20181212_010304-PSII5_0_0.tif
A1-silk_dark-20181212_010304-PSII6_0_0.tif
A1-silk_dark-20181212_010304-PSII7_0_0.tif
A1-silk_dark-20181212_010304-PSII8_0_0.tif
A1-silk_dark-20181212_010304-PSII9_0_0.tif
A1-silk_dark-20181212_010304-PSII10_0_0.tif
```

> I need to iterate through the timestamp (so the above would be one group) but process pairs of images. 1 and 2 are special, so my pairs are 5,6; 7,8; 9,10. additionally, each of my latter pairs need 1,2 for certain calcs. I'm looking at --coprocess but that is specifically for imgtype and I'd need to process PSII1_0_0 etc with a wildcard.

There are two issues right? 1) you need all these input to your workflow script; 2) you need to pair them up. We mapped out a couple solutions that should solve 1, but maybe only the "mapping" solution would solve 2. Was that your preference or were you thinking the user workflow script would deal with other higher-level usage of the data (e.g. pairing)?

**Comment by dschneiderch** [comment]
Correct.
im not sure it matters if the pairing happens as a map or in the user script. User needs to take care of it eitherway. It might be slightly easier in the user script.

**Comment by nfahlgren** [comment]
Gotcha, so your preference would be the simpler metadata grouping option? In your example you might use the regex parser to split the PSII and # into two terms and then group on the term associated with `PSII` and the timestamp or something.

**Comment by dschneiderch** [comment]
something like this would work i think

```
plantcv-workflow.py 
--dir data/psII
--workflow scripts/psIIworkflow.py
--outdir output/psII
--adaptor filename
--type tif
--delimiter (.+)-(.+)-(\d{8}_\d{6})-(\s{4})(\s{5})
--metadata sampleid,measurementlabel,timestamp,cameralabel,id
--json output/psII/results.json
--timestampformat %Y%m%d_%H%M%S
--group sampleid,measurementlabel,timestamp,cameralabel
```
then all those PSII frames that were captured at the same time get passed together. as I write this, i realize it could get unwieldy though. now in the script you'd have to iterate through your pairs.
I keep a metadata file (pimframes_map.csv) in data/ that looks like this:
```
id| frame | parameter
1 | Fo | FvFm
2 | Fm | FvFm
3 | AbsR | AbsR
4 | AbsN | AbsN
5 | Fp | FvFm
6 | Fmp | FvFm
7 | Fp | t40_ALon
8 | Fmp | t40_ALon
9 | Fp | t60_ALon
10 | Fmp | t60_ALon
11 | Fp | t80_ALon
12 | Fmp | t80_ALon
13 | Fp | t100_ALon
14 | Fmp | t100_ALon
15 | Fp | t120_ALon
16 | Fmp | t120_ALon
17 | Fp | t140_ALon
18 | Fmp | t140_ALon
19 | Fp | t160_ALon
20 | Fmp | t160_ALon
21 | Fp | t180_ALon
22 | Fmp | t180_ALon
23 | Fp | t200_ALon
24 | Fmp | t200_ALon
25 | Fp | t220_ALon
26 | Fmp | t220_ALon
27 | Fp | t240_ALon
28 | Fmp | t240_ALon
29 | Fp | t260_ALon
30 | Fmp | t260_ALon
31 | Fp | t280_ALon
32 | Fmp | t280_ALon
33 | Fp | t300_ALon
34 | Fmp | t300_ALon
```
Currently I make a dataframe that i use as a dictionary (because I don't really understand how to use dict) to map the id# to the frame and parameter and would append the filenames as a column

```
for p in df.parameter:
    i1 = readimage(df.filename[0])
    i2 = readimage(df.filename[1])
```

Not great - for one thing if they come out of order then things get funky. I also make my mask with Fm so I always use `arrange` to make sure Fo and Fm are passed first, then I write the mask to file and read it back in if the parameter != FvFm


```
for p in df.parameter:
    i1 = readimage(df.filename[0])
    i2 = readimage(df.filename[1])
    if p=='FvFm':
        mask=createmask()
        cv2.write(mask)
    else:
        mask = readimage(mask from the correct file) #although i guess it would be in the env still 
    
    do the analysis.....   

```

Open to ideas here.
What if you made the input a class, similar to the discussion about contours and hierarchies so the user didn't need to run the loop and the mask was always made first with Fm?

**Comment by nfahlgren** [comment]
I have been working on this and related issues. I have grouping reasonably figured out I think, and have it set up to replace the older "coprocess" functionality. But now I'm a bit stuck and there's multiple potential directions we could take. The short summary of the issue is, we have a group of 1+ images, how do we pass that/input it to a workflow in a way that doesn't create a lot of coding for the user?

We also have a preexisting issue, that I think is made worse here: when developing a workflow I think typically metadata is not available (in a PlantCV-way anyhow) but when you parallelize there's a built-in method for supplying the metadata. But that means there's a disconnect between the inputs engineered when developing a workflow and what's needed later for doing bulk analysis.

One way to deal with this would be to make reading metadata part of the `pcv.readimage` function. I'm thinking for each image file there would be a corresponding JSON file. `pcv.readimage` could read in the image as normal and then (if it exists) read in the metadata automatically. The JSON metadata files could be created by an "indexing" function in the `parallel` subpackage (basically a modified version of the current `metadata_parser` function. This could be run once upfront for a new dataset. Potentially it could be useful to create a master database of the image metadata using something like: https://tinydb.readthedocs.io/en/latest/?

**Comment by dschneiderch** [comment]
a way to include metadata in both parallel and interactively would be great. metadata unavailable when developing a workflow is definitely a painpoint for me. I've resorted to some hybrid of manually entering it and copying part of the underlying parser code into my scripts. The tinydb looks like a very practical solution but how will it integrate with snapshots.csv file you use when you have with phenocenter adapter? i imagine the plantcv code would become easier to manage if you could convert snapshots.csv into a 

I tried following your branch to see how the grouping work but it eluded me....

**Comment by nfahlgren** [comment]
Definitely agree about the tinydb vs CSV issue, and I think we can work on this from both directions. We could adapt the database export tool to start creating the metadata file(s) automatically going forward. But we could also provide a method for creating them after the fact for "legacy" datasets.

I might not have pushed the grouping part of the pull request yet. But what it will let you do is input a set of "group_by" metadata terms. It creates an ID from term1_term2_etc and groups data that have the same group_by IDs. As an example, to replace the old coprocess mechanism we would group by `timestamp` and `frame`, which could group the VIS and NIR image from the same time and the same viewing angle.

**Comment by dschneiderch** [comment]
grouping by timestamp and frame will work well for PSII camera that takes 6+ images per snapshot but i'm not separate cameras like  VIS and NIR would have the same timestamp exactly. does there need to be a filter for "within an hour" or so?
