### ISSUE TITLE
Timestamp format and flat-directory analysis

### ISSUE THREAD

**Issue by AdamDimech** [danforthcenter/plantcv#444]
I have been downloading LemnaTec-derived images from our database using [this version](https://github.com/AdamDimech/data-science-tools/blob/master/LT-db-extractor.py) of the "Data Science Tools".

Images are downloaded and PNG files written with names as follows:
-B2018004r3s33_2018-08-16 11-39-33_test_0-deg_20593801_0.png
-B2018004r3s33_2018-08-16 11-39-33_test_90-deg_20593901_0.png
-B2018004r3s33_2018-08-16 11-39-33_test_TV_20593701_0.png

I have a working PlantCV pipeline and I believe that I have named the files using [valid metadata](https://plantcv.readthedocs.io/en/stable/pipeline_parallel/#running-plantcv-over-phenofront-image-data-set-structure).

When attempting to run the analysis, I use the following command:
`C:/plantcv/plantcv-workflow.py -d "T:/path/to/files" -a filename -p C:/T:/path/to/files/my_pipeline.py -i T:/path/to/files/results -j T:/path/to/files/results/results.json -f plantbarcode_timestamp_measurementlabel_imgtype_cartag_other -M imgtype:0-deg -t png -T 16 -l "_" -w`

It seems that PlantCV is tripping-up on the timestamps. Error output:

`Traceback (most recent call last):
  File "C:\plantcv\plantcv-workflow.py", line 317, in <module>
    main()
  File "C:\plantcv\plantcv-workflow.py", line 271, in main
    coprocess=args.coprocess)
  File "C:\plantcv\plantcv\parallel\parsers.py", line 194, in metadata_parser
    in_date_range = _check_date_range(start_date, end_date, img_meta['timestamp'])
  File "C:\plantcv\plantcv\parallel\parsers.py", line 225, in _check_date_range
    time_delta = timestamp - datetime.datetime(1970, 1, 1)
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).`

I cannot see what I am doing wrong. Is this a bug?

I am aware that the timestamp issue has been raised before (ie [here](https://github.com/danforthcenter/plantcv/issues/423) and [here](https://github.com/danforthcenter/plantcv/issues/424#issuecomment-516199544)). Help!

**Comment by HaleySchuhl** [comment]
Hi @AdamDimech ,

I have not come across this particular error before. I was able to replicate the error but I am still unsure what is causing it. The error goes away when I rename the image to `-B2018004r3s33_2018-08-16_test_0-deg_20593801_0.png`. I will continue to look into this and check back with any progress!

**Comment by nfahlgren** [comment]
I know with Windows you can't use colons in filenames, so won't be able to use timestamps in the format `2018-08-16 11:39:33`. I have been trying to avoid that where we can for cross-platform compatibility.

**Comment by nfahlgren** [comment]
It looks like `dt_parser` works if I remove `-` characters all together. I will make a pull request to make that change.

**Comment by nfahlgren** [comment]
Sorry, the pull request automatically closed the issue. If there is still and issue, please feel free to reopen.
