### ISSUE TITLE
In Hyperspectral Image Workflow the final script seems to face a decoding issue with my .hdr file

### ISSUE THREAD

**Issue by PrivateHank** [danforthcenter/plantcv#555]
I apologize if it is a trivial detail, but am a beginner in hyperspectral image analysis and to plantcv too. I am trying to follow the hyperspectral tutorial to generate results for my image but am facing a "UnicodeDecodeError:  'charmap' codec can't decode byte 0x90 in position 86: character maps to <undefined>" 

**To Reproduce**
Steps to reproduce the behavior (including sample data and code really help):
1. Script as provided by the [tutorial](https://plantcv.readthedocs.io/en/stable/hyperspectral_tutorial/#tutorial-hyperspectral-image-workflow)
2. In the terminal:
python hyperspectral_tutorial.py -i image -o .\output_images -r results.txt -w -D 'print'
Note: file in folder is .hdr file named image.hdr
3. Traceback (most recent call last):
  File "hyperspectral_tutorial.py", line 78, in <module>
    main()
  File "hyperspectral_tutorial.py", line 36, in main
    spectral_array = pcv.readimage(filename=args.image, mode='envi')
  File "..\venv\lib\site-packages\plantcv\plantcv\readimage.py", line 42, in readimage
    array_data = read_data(filename)
  File "..\venv\lib\site-packages\plantcv\plantcv\hyperspectral\read_data.py", line 114, in read_data
    hdata = f.read()
  File "..\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 86: character maps to \<undefined\>

**Expected behavior**
Expected output as tutorial

**Local environment (please complete the following information):**
 - OS: [Windows10]
 - Environment: virtualenv
 - PlantCV Version 3.8.0

**Comment by HaleySchuhl** [comment]
Hi @PrivateHank ,

Thanks for reaching out! I'm not immediately sure what to make of the UnicodeDecodeError but we have only been able to test the hyperspectral tools on images from a couple cameras so far. The function right now is expecting the `filename` of the image to have no file extension and the respective .hdr file to be named `filename.hdr`. Is this the case with your images/.hdr files? I realize images are likely too large to send easily but can you send you .hdr file you were using so I can try to reproduce this error?

**Comment by PrivateHank** [comment]
Hi @HaleySchuhl 

Thank you for the prompt reply. 

Firstly there is a single .hdr file as I am exploring the results, and yes, I have followed the input expectations of the script. I am attaching my file for your reference.
[hdr_file.zip](https://github.com/danforthcenter/plantcv/files/4381141/hdr_file.zip)

**Comment by HaleySchuhl** [comment]
@PrivateHank 

I downloaded the hdr_file you sent but it appears to be an actual image. The types of .hdr files from ENVI cameras that we have tested on usually look something like this:

```
ENVI
description = {[HEADWALL Hyperspec III]}
samples = 1600
lines = 1714
bands = 978
header offset = 0
file type = ENVI Standard
data type = 4
interleave = bil
sensor type = Unknown
default bands = {159,253,520}
byte order = 0
wavelength units = nm
wavelength = {
379.027
,379.663
,380.3
,380.936
,381.573
,382.209
,382.846
,383.483
,384.119
,384.756
,385.392
,386.029
,386.665
,387.302
,387.939
,388.575
,389.212
,389.848
,390.485
,391.121
,391.758
,392.395
,393.031
,393.668
,394.304
,394.941
,395.577
,396.214
,396.85
,397.487
,398.124
,398.76
,399.397
,400.033
,400.67
,401.306
,401.943
,402.58
,403.216
,403.853
,404.489
,405.126
,405.762
,406.399
,407.035
,407.672
,408.309
,408.945
,409.582
,410.218
,410.855
,411.491
,412.128
,412.765
,413.401
,414.038
,414.674
,415.311
,415.947
,416.584
,417.221
,417.857
,418.494
,419.13
,419.767
,420.403
,421.04
,421.676
,422.313
,422.95
,423.586
,424.223
,424.859
,425.496
,426.132
,426.769
,427.406
,428.042
,428.679
,429.315
,429.952
,430.588
,431.225
,431.861
,432.498
,433.135
,433.771
,434.408
,435.044
,435.681
,436.317
,436.954
,437.591
,438.227
,438.864
,439.5
,440.137
,440.773
,441.41
,442.046
,442.683
,443.32
,443.956
,444.593
,445.229
,445.866
,446.502
,447.139
,447.776
,448.412
,449.049
,449.685
,450.322
,450.958
,451.595
,452.232
,452.868
,453.505
,454.141
,454.778
,455.414
,456.051
,456.687
,457.324
,457.961
,458.597
,459.234
,459.87
,460.507
,461.143
,461.78
,462.417
,463.053
,463.69
,464.326
,464.963
,465.599
,466.236
,466.872
,467.509
,468.146
,468.782
,469.419
,470.055
,470.692
,471.328
,471.965
,472.602
,473.238
,473.875
,474.511
,475.148
,475.784
,476.421
,477.058
,477.694
,478.331
,478.967
,479.604
,480.24
,480.877
,481.513
,482.15
,482.787
,483.423
,484.06
,484.696
,485.333
,485.969
,486.606
,487.243
,487.879
,488.516
,489.152
,489.789
,490.425
,491.062
,491.698
,492.335
,492.972
,493.608
,494.245
,494.881
,495.518
,496.154
,496.791
,497.428
,498.064
,498.701
,499.337
,499.974
,500.61
,501.247
,501.884
,502.52
,503.157
,503.793
,504.43
,505.066
,505.703
,506.339
,506.976
,507.613
,508.249
,508.886
,509.522
,510.159
,510.795
,511.432
,512.069
,512.705
,513.342
,513.978
,514.615
,515.251
,515.888
,516.524
,517.161
,517.798
,518.434
,519.071
,519.707
,520.344
,520.98
,521.617
,522.254
,522.89
,523.527
,524.163
,524.8
,525.436
,526.073
,526.71
,527.346
,527.983
,528.619
,529.256
,529.892
,530.529
,531.165
,531.802
,532.439
,533.075
,533.712
,534.348
,534.985
,535.621
,536.258
,536.895
,537.531
,538.168
,538.804
,539.441
,540.077
,540.714
,541.35
,541.987
,542.624
,543.26
,543.897
,544.533
,545.17
,545.806
,546.443
,547.08
,547.716
,548.353
,548.989
,549.626
,550.262
,550.899
,551.536
,552.172
,552.809
,553.445
,554.082
,554.718
,555.355
,555.991
,556.628
,557.265
,557.901
,558.538
,559.174
,559.811
,560.447
,561.084
,561.721
,562.357
,562.994
,563.63
,564.267
,564.903
,565.54
,566.176
,566.813
,567.45
,568.086
,568.723
,569.359
,569.996
,570.632
,571.269
,571.906
,572.542
,573.179
,573.815
,574.452
,575.088
,575.725
,576.362
,576.998
,577.635
,578.271
,578.908
,579.544
,580.181
,580.817
,581.454
,582.091
,582.727
,583.364
,584
,584.637
,585.273
,585.91
,586.547
,587.183
,587.82
,588.456
,589.093
,589.729
,590.366
,591.002
,591.639
,592.276
,592.912
,593.549
,594.185
,594.822
,595.458
,596.095
,596.732
,597.368
,598.005
,598.641
,599.278
,599.914
,600.551
,601.188
,601.824
,602.461
,603.097
,603.734
,604.37
,605.007
,605.643
,606.28
,606.917
,607.553
,608.19
,608.826
,609.463
,610.099
,610.736
,611.373
,612.009
,612.646
,613.282
,613.919
,614.555
,615.192
,615.828
,616.465
,617.102
,617.738
,618.375
,619.011
,619.648
,620.284
,620.921
,621.558
,622.194
,622.831
,623.467
,624.104
,624.74
,625.377
,626.013
,626.65
,627.287
,627.923
,628.56
,629.196
,629.833
,630.469
,631.106
,631.743
,632.379
,633.016
,633.652
,634.289
,634.925
,635.562
,636.199
,636.835
,637.472
,638.108
,638.745
,639.381
,640.018
,640.654
,641.291
,641.928
,642.564
,643.201
,643.837
,644.474
,645.11
,645.747
,646.384
,647.02
,647.657
,648.293
,648.93
,649.566
,650.203
,650.839
,651.476
,652.113
,652.749
,653.386
,654.022
,654.659
,655.295
,655.932
,656.569
,657.205
,657.842
,658.478
,659.115
,659.751
,660.388
,661.025
,661.661
,662.298
,662.934
,663.571
,664.207
,664.844
,665.48
,666.117
,666.754
,667.39
,668.027
,668.663
,669.3
,669.936
,670.573
,671.21
,671.846
,672.483
,673.119
,673.756
,674.392
,675.029
,675.665
,676.302
,676.939
,677.575
,678.212
,678.848
,679.485
,680.121
,680.758
,681.395
,682.031
,682.668
,683.304
,683.941
,684.577
,685.214
,685.851
,686.487
,687.124
,687.76
,688.397
,689.033
,689.67
,690.306
,690.943
,691.58
,692.216
,692.853
,693.489
,694.126
,694.762
,695.399
,696.036
,696.672
,697.309
,697.945
,698.582
,699.218
,699.855
,700.491
,701.128
,701.765
,702.401
,703.038
,703.674
,704.311
,704.947
,705.584
,706.221
,706.857
,707.494
,708.13
,708.767
,709.403
,710.04
,710.677
,711.313
,711.95
,712.586
,713.223
,713.859
,714.496
,715.132
,715.769
,716.406
,717.042
,717.679
,718.315
,718.952
,719.588
,720.225
,720.862
,721.498
,722.135
,722.771
,723.408
,724.044
,724.681
,725.317
,725.954
,726.591
,727.227
,727.864
,728.5
,729.137
,729.773
,730.41
,731.047
,731.683
,732.32
,732.956
,733.593
,734.229
,734.866
,735.503
,736.139
,736.776
,737.412
,738.049
,738.685
,739.322
,739.958
,740.595
,741.232
,741.868
,742.505
,743.141
,743.778
,744.414
,745.051
,745.688
,746.324
,746.961
,747.597
,748.234
,748.87
,749.507
,750.143
,750.78
,751.417
,752.053
,752.69
,753.326
,753.963
,754.599
,755.236
,755.873
,756.509
,757.146
,757.782
,758.419
,759.055
,759.692
,760.329
,760.965
,761.602
,762.238
,762.875
,763.511
,764.148
,764.784
,765.421
,766.058
,766.694
,767.331
,767.967
,768.604
,769.24
,769.877
,770.514
,771.15
,771.787
,772.423
,773.06
,773.696
,774.333
,774.969
,775.606
,776.243
,776.879
,777.516
,778.152
,778.789
,779.425
,780.062
,780.699
,781.335
,781.972
,782.608
,783.245
,783.881
,784.518
,785.154
,785.791
,786.428
,787.064
,787.701
,788.337
,788.974
,789.61
,790.247
,790.884
,791.52
,792.157
,792.793
,793.43
,794.066
,794.703
,795.34
,795.976
,796.613
,797.249
,797.886
,798.522
,799.159
,799.795
,800.432
,801.069
,801.705
,802.342
,802.978
,803.615
,804.251
,804.888
,805.525
,806.161
,806.798
,807.434
,808.071
,808.707
,809.344
,809.98
,810.617
,811.254
,811.89
,812.527
,813.163
,813.8
,814.436
,815.073
,815.71
,816.346
,816.983
,817.619
,818.256
,818.892
,819.529
,820.166
,820.802
,821.439
,822.075
,822.712
,823.348
,823.985
,824.621
,825.258
,825.895
,826.531
,827.168
,827.804
,828.441
,829.077
,829.714
,830.351
,830.987
,831.624
,832.26
,832.897
,833.533
,834.17
,834.806
,835.443
,836.08
,836.716
,837.353
,837.989
,838.626
,839.262
,839.899
,840.536
,841.172
,841.809
,842.445
,843.082
,843.718
,844.355
,844.992
,845.628
,846.265
,846.901
,847.538
,848.174
,848.811
,849.447
,850.084
,850.721
,851.357
,851.994
,852.63
,853.267
,853.903
,854.54
,855.177
,855.813
,856.45
,857.086
,857.723
,858.359
,858.996
,859.632
,860.269
,860.906
,861.542
,862.179
,862.815
,863.452
,864.088
,864.725
,865.362
,865.998
,866.635
,867.271
,867.908
,868.544
,869.181
,869.818
,870.454
,871.091
,871.727
,872.364
,873
,873.637
,874.273
,874.91
,875.547
,876.183
,876.82
,877.456
,878.093
,878.729
,879.366
,880.003
,880.639
,881.276
,881.912
,882.549
,883.185
,883.822
,884.458
,885.095
,885.732
,886.368
,887.005
,887.641
,888.278
,888.914
,889.551
,890.188
,890.824
,891.461
,892.097
,892.734
,893.37
,894.007
,894.644
,895.28
,895.917
,896.553
,897.19
,897.826
,898.463
,899.099
,899.736
,900.373
,901.009
,901.646
,902.282
,902.919
,903.555
,904.192
,904.829
,905.465
,906.102
,906.738
,907.375
,908.011
,908.648
,909.284
,909.921
,910.558
,911.194
,911.831
,912.467
,913.104
,913.74
,914.377
,915.014
,915.65
,916.287
,916.923
,917.56
,918.196
,918.833
,919.47
,920.106
,920.743
,921.379
,922.016
,922.652
,923.289
,923.925
,924.562
,925.199
,925.835
,926.472
,927.108
,927.745
,928.381
,929.018
,929.655
,930.291
,930.928
,931.564
,932.201
,932.837
,933.474
,934.11
,934.747
,935.384
,936.02
,936.657
,937.293
,937.93
,938.566
,939.203
,939.84
,940.476
,941.113
,941.749
,942.386
,943.022
,943.659
,944.295
,944.932
,945.569
,946.205
,946.842
,947.478
,948.115
,948.751
,949.388
,950.025
,950.661
,951.298
,951.934
,952.571
,953.207
,953.844
,954.481
,955.117
,955.754
,956.39
,957.027
,957.663
,958.3
,958.936
,959.573
,960.21
,960.846
,961.483
,962.119
,962.756
,963.392
,964.029
,964.666
,965.302
,965.939
,966.575
,967.212
,967.848
,968.485
,969.121
,969.758
,970.395
,971.031
,971.668
,972.304
,972.941
,973.577
,974.214
,974.851
,975.487
,976.124
,976.76
,977.397
,978.033
,978.67
,979.307
,979.943
,980.58
,981.216
,981.853
,982.489
,983.126
,983.762
,984.399
,985.036
,985.672
,986.309
,986.945
,987.582
,988.218
,988.855
,989.492
,990.128
,990.765
,991.401
,992.038
,992.674
,993.311
,993.947
,994.584
,995.221
,995.857
,996.494
,997.13
,997.767
,998.403
,999.04
,999.677
,1000.31
,1000.95
}
;AOI height = 1008
;AOI left = 480
;AOI top = 576
;AOI width = 1600
;Array Pixel Pitch (um) = 6.5
;AverageDispersion = 0.636564
;Col binning = 1
;HSIII_VERSION = E61202 vs64 5.5.1
;Lens EFL (mm) = 23
;Lens folder = 23mm
;Nuc folder = C:/headwall/sensorConfig/G4-426/23mm/nuc
;POST AOI height = 978
;POST AOI left = 0
;POST AOI top = 0
;POST AOI width = 1600
;POST Col binning = 1
;POST Row binning = 1
;Pixel0 = 12.3658
;Row binning = 1
;Serial Number = G4-426
```

**Comment by nfahlgren** [comment]
Hi @PrivateHank,

Looking at your image more it appears to be a Radiance HDR (RGBE) file. The HDR terminology is a bit confusing. In our case, as @HaleySchuhl mentioned, it is a file extension used for the header file (a text file) for ENVI image data. For Radiance HDR images, HDR refers to High-Dynamic Range instead.

I did a brief test and your `image.hdr` file can be read with the OpenCV backend built into `pcv.readimage`:

```python
img, imgpath, imgname = pcv.readimage(filename="image.hdr")
```

It's is read in as a float32 data type.

**Comment by PrivateHank** [comment]
Okay got it. Thank you @HaleySchuhl @nfahlgren  pointing out the issue.
