### ISSUE TITLE
Problems parallelizing machine learning tutorial

### ISSUE THREAD

**Issue by MIANCOGU** [danforthcenter/plantcv#922]
Hi there,
I am trying to parallelize the code of the machine learning tutorial [(here)](https://plantcv.readthedocs.io/en/v3.2.0/machine_learning_tutorial/).
There is my code: 

```
import os
import cv2
import numpy as np
from scipy import stats
from matplotlib import pyplot as plt
from plantcv import plantcv as pcv
import argparse



def options():
    parser = argparse.ArgumentParser(description="Imaging processing with plantcv")
    parser.add_argument("-i", "--image", help="Input image file.", required=True)
    parser.add_argument("-o", "--outdir", help="Output directory for image files.", required=False)
    parser.add_argument("-r", "--result", help="result file.", required=False)
    parser.add_argument("-r2", "--coresult", help="result file.", required=False)
    parser.add_argument("-p", "--pdfs", help="Naive Bayes PDF file.", required=True)
    parser.add_argument("-w", "--writeimg", help="write out images.", default=False, action="store_true")
    parser.add_argument("-D", "--debug", help="Turn on debug, prints intermediate images.", default=None)
    args = parser.parse_args()
    return args

def main():
    # Get options
    args = options()
    pcv.params.debug = args.debug
    pcv.params.debug_outdir = args.outdir
    device = 0

    # Read in the input image
    img, path, filename = pcv.readimage(filename=args.image)

    # Classify each pixel as plant or background (background and system components)
    mask = pcv.naive_bayes_classifier(rgb_img=img, pdf_file=args.pdfs)

    plant_img = pcv.apply_mask(mask=(mask['Healthy']), img=img, mask_color='black')
    pustule_img = pcv.apply_mask(mask=(mask['Pustule']), img=img, mask_color='black')
    chlorosis_img = pcv.apply_mask(mask=(mask['Chlorosis']), img=img, mask_color='black')
    background_img = pcv.apply_mask(mask=(mask['Background']), img=img, mask_color='black')
    
    healthy_maskpath, plant_analysis_images = pcv.output_mask(img=img, mask=mask['Healthy'], 
                                                        filename='healthy.png', mask_only=True)
    pust_maskpath, pust_analysis_images = pcv.output_mask(img=img, mask=mask['Pustule'], 
                                                      filename='pustule.png', mask_only=True)
    chlor_maskpath, chlor_analysis_images = pcv.output_mask(img=img, mask=mask['Chlorosis'], 
                                                        filename='chlorosis.png', mask_only=True)
    bkgrd_maskpath, bkgrd_analysis_images = pcv.output_mask(img=img, mask=mask['Background'], 
                                                        filename='background.png', mask_only=True)
    classified_img = pcv.visualize.colorize_masks(masks=[mask['Healthy'], mask['Pustule'], 
                                                     mask['Chlorosis'], mask['Background']], 
                                              colors=['dark green', 'red', 'gold', 'gray'])

    # Calculate percent of the plant found to be diseased 
    sick_plant = np.count_nonzero(mask['Pustule']) + np.count_nonzero(mask['Chlorosis'])
    healthy_plant = np.count_nonzero(mask['Healthy'])
    percent_diseased = sick_plant / (sick_plant + healthy_plant)


    pustules = np.count_nonzero(mask['Pustule'])
    pcv.outputs.add_observation(sample='default', variable='pustules', trait='pixels classified as pustule',
                            method='number of pixels', scale='percent', datatype=float,
                            value=pustules, label='percent')
    chlorosis = np.count_nonzero(mask['Chlorosis'])
    pcv.outputs.add_observation(sample='default', variable='chlorosis', trait='pixels classified as chlorosis',
                            method='number of pixels', scale='percent', datatype=float,
                            value=chlorosis, label='percent')
    healthy = np.count_nonzero(mask['Healthy'])
    pcv.outputs.add_observation(sample='default', variable='healthy', trait='pixels classified as healthy plant',
                            method='number of pixels', scale='percent', datatype=float,
                            value=healthy, label='percent')
    background = np.count_nonzero(mask['Background'])
    pcv.outputs.add_observation(sample='default', variable='background', trait='pixels classified as bakcground',
                            method='number of pixels', scale='percent', datatype=float,
                            value=background, label='percent')
    pcv.outputs.add_observation(sample='default', variable='percent_diseased', trait='percent of plant detected to be diseased',
                            method='ratio of pixels', scale='percent', datatype=float,
                            value=percent_diseased, label='percent')
    pcv.outputs.save_results(filename="results.json")

if __name__ == '__main__':
    main()
```

As you can see, it is very similar to the tutorial code. The only difference is that I am interested also in the others pixel categories. I have checked and it works fine with a single picture. When I run the code, it gives me a JSON file with the number of pixels in each category.
Then, I checked with a folder which contains different images, because I would like to have a JSON file with the number of pixels in each category for each picture. 
As I am in windows system, I open the prompt (after activate plantcv) and write this:

```
python.exe ^
%CONDA_PREFIX%\Scripts\plantcv-pipeline2.py ^
-i C:\Users\mlaz0001\Desktop\my_images ^
-o C:\Users\mlaz0001\Desktop\results ^
-p C:\Users\mlaz0001\Anaconda3\envs\plantcv\Scripts\pdfs_naive_bayes_pdfs.txt
```

But it replies:

```
[ WARN:0@3.809] global D:\bld\libopencv_1656375874586\work\modules\imgcodecs\src\loadsave.cpp (239) cv::findDecoder imread_('C:\Users\mlaz0001\Desktop\my_images'): can't open/read file: check file path/integrity
Traceback (most recent call last):
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\Scripts\plantcv-pipeline2.py", line 91, in <module>
    main()
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\Scripts\plantcv-pipeline2.py", line 39, in main
    img, path, filename = pcv.readimage(filename=args.image)
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\plantcv\plantcv\readimage.py", line 51, in readimage
    fatal_error("Failed to open " + filename)
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\plantcv\plantcv\fatal_error.py", line 13, in fatal_error
    raise RuntimeError(error)
RuntimeError: Failed to open C:\Users\mlaz0001\Desktop\my_images
```

I have checked the code and search in Google the message error, but I have not found anything. Probably it is a very simple issue but I am not sure about where is the problem. Any help on how to fix this is greatly appreciated!

**Comment by nfahlgren** [comment]
Hi @MIANCOGU!

Your workflow looks good, the one thing you would need to change to run it i parallel is to change this line:

```python
pcv.outputs.save_results(filename="results.json")
```

To

```python
pcv.outputs.save_results(filename=args.result)
```

To parallelize the workflow, PlantCV does not do this directly with the workflow. Instead, we provide a program called `plantcv-workflow.py` that handles the parallelization, metadata processing, and results aggregation: https://plantcv.readthedocs.io/en/stable/pipeline_parallel/

Outlined on that page, you start by creating a configuration file (documented more here: https://plantcv.readthedocs.io/en/stable/parallel_config/). You will plug in your image directory, workflow script, and other settings. Then `plantcv-workflow.py` will run your workflow on each image in parallel (optionally) workers, and it supplies the inputs that you configured with the `options` function in your workflow.

One thing to note is that `--pdfs` is not a standard workflow input that `plantcv-workflow.py` provides. To configure it, the parallel configuration file has the attribute `other_args` where you would supply the input and your pdfs file:

```
"other_args": ["--pdfs", "C:\Users\mlaz0001\Anaconda3\envs\plantcv\Scripts\pdfs_naive_bayes_pdfs.txt"]
```

**Comment by MIANCOGU** [comment]
Thanks! Finally I understand, sorry I was quite confuse about how use the different programs.
If someone has a similar problem, you only need to write like that:
```
python.exe ^
%CONDA_PREFIX%\Scripts\plantcv-workflow.py ^
-p %CONDA_PREFIX%\Scripts\plantcv-pipeline2.py ^
--config %CONDA_PREFIX%\Scripts\my_config.json
```
Just it is curiosity, but, why appears that message? The code is working but the first time I though that it was an error

```
- distributed.client - ERROR -
Traceback (most recent call last):
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\utils.py", line 776, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\client.py", line 1211, in _reconnect
    await self._ensure_connected(timeout=timeout)
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\client.py", line 1241, in _ensure_connected
    comm = await connect(
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\comm\core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\asyncio\tasks.py", line 432, in wait_for
    await waiter
asyncio.exceptions.CancelledError

Traceback (most recent call last):
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\utils.py", line 776, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\client.py", line 1400, in _handle_report
    await self._reconnect()
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\utils.py", line 776, in wrapper
    return await func(*args, **kwargs)
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\client.py", line 1211, in _reconnect
    await self._ensure_connected(timeout=timeout)
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\client.py", line 1241, in _ensure_connected
    comm = await connect(
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\site-packages\distributed\comm\core.py", line 291, in connect
    comm = await asyncio.wait_for(
  File "C:\Users\mlaz0001\Anaconda3\envs\plantcv\lib\asyncio\tasks.py", line 432, in wait_for
    await waiter
asyncio.exceptions.CancelledError
```

**Comment by nfahlgren** [comment]
I am not sure. We sometimes see these timeout errors from Dask (the tool we use for parallelization)
